---
# tasks file for set_proxy4yum_dnf
- name: Ensure proxy is set in section "[main]" in /etc/yum.conf
  ini_file:
    path: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ set_proxy4yum_dnf_scheme }}://{{ set_proxy4yum_dnf_hostname }}:{{ set_proxy4yum_dnf_port }}"
    backup: yes
  become: yes
  when: ansible_facts['distribution_major_version'] == "7"

- name: Ensure proxy is set in section "[main]" in /etc/dnf/dnf.conf
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: "{{ set_proxy4yum_dnf_scheme }}://{{ set_proxy4yum_dnf_hostname }}:{{ set_proxy4yum_dnf_port }}"
    backup: yes
  become: yes
  when: ansible_facts['distribution_major_version'] == "8"
